import { StyleSheet } from 'react-native';
import { Theme } from '@/components/ThemeProvider';

export const createStyles = (theme: Theme, isDark: boolean) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.colors.background,
    },
    header: {
      paddingTop: 20,
      paddingBottom: 30,
      paddingHorizontal: 20,
      borderBottomLeftRadius: 20,
      borderBottomRightRadius: 20,
    },
    headerTitle: {
      fontSize: 24,
      fontWeight: 'bold',
      color: 'white',
      textAlign: 'center',
      fontFamily: 'Inter-Bold',
    },
    headerSubtitle: {
      fontSize: 14,
      color: 'rgba(255, 255, 255, 0.8)',
      textAlign: 'center',
      marginTop: 4,
      fontFamily: 'Inter-Regular',
    },
    content: {
      flex: 1,
      padding: 20,
    },
    section: {
      marginBottom: 32,
    },
    sectionTitle: {
      fontSize: 18,
      fontWeight: 'bold',
      color: theme.colors.text,
      marginBottom: 12,
      fontFamily: 'Inter-Bold',
    },
    subSectionTitle: {
      fontSize: 14,
      fontWeight: '600',
      color: theme.colors.textSecondary,
      marginTop: 16,
      marginBottom: 8,
      marginLeft: 16,
      fontFamily: 'Inter-SemiBold',
    },
    sectionContent: {
      backgroundColor: theme.colors.surface,
      borderRadius: 16,
      elevation: 2,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
    },
    settingsItem: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      padding: 16,
      borderBottomWidth: 1,
      borderBottomColor: isDark ? '#374151' : '#f3f4f6',
    },
    lockedItem: {
      opacity: 0.6,
    },
    settingsItemLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      flex: 1,
    },
    settingsItemIcon: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: isDark ? '#374151' : '#f3f4f6',
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 12,
    },
    lockedIcon: {
      backgroundColor: isDark ? '#1f2937' : '#f9fafb',
    },
    titleRow: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    settingsItemTitle: {
      fontSize: 16,
      fontWeight: '500',
      color: theme.colors.text,
      fontFamily: 'Inter-SemiBold',
    },
    lockedText: {
      color: theme.colors.textSecondary,
    },
    proLabel: {
      backgroundColor: '#f59e0b',
      color: 'white',
      fontSize: 10,
      fontWeight: '600',
      paddingHorizontal: 6,
      paddingVertical: 2,
      borderRadius: 8,
      marginLeft: 8,
      fontFamily: 'Inter-SemiBold',
    },
    settingsItemSubtitle: {
      fontSize: 14,
      color: theme.colors.textSecondary,
      marginTop: 2,
      fontFamily: 'Inter-Regular',
    },
    settingsItemRight: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    appInfo: {
      alignItems: 'center',
      paddingVertical: 32,
      paddingHorizontal: 20,
    },
    appInfoTitle: {
      fontSize: 20,
      fontWeight: 'bold',
      color: theme.colors.text,
      marginBottom: 4,
      fontFamily: 'Inter-Bold',
    },
    appInfoVersion: {
      fontSize: 14,
      color: theme.colors.textSecondary,
      marginBottom: 12,
      fontFamily: 'Inter-Regular',
    },
    appInfoDescription: {
      fontSize: 14,
      color: theme.colors.textSecondary,
      textAlign: 'center',
      lineHeight: 20,
      fontFamily: 'Inter-Regular',
    },
    modalContainer: {
      flex: 1,
      backgroundColor: theme.colors.background,
    },
    modalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: 20,
      backgroundColor: theme.colors.surface,
      borderBottomWidth: 1,
      borderBottomColor: isDark ? '#374151' : '#e5e7eb',
    },
    modalTitle: {
      fontSize: 20,
      fontWeight: 'bold',
      color: theme.colors.text,
      fontFamily: 'Inter-Bold',
    },
    modalContent: {
      flex: 1,
      padding: 20,
    },
    modalText: {
      fontSize: 16,
      color: theme.colors.text,
      textAlign: 'center',
      fontFamily: 'Inter-Regular',
    },
    optionItem: {
      backgroundColor: theme.colors.surface,
      padding: 16,
      borderRadius: 12,
      marginBottom: 8,
      borderWidth: 2,
      borderColor: 'transparent',
    },
    selectedOption: {
      borderColor: '#3b82f6',
      backgroundColor: isDark ? '#1e3a8a' : '#eff6ff',
    },
    optionText: {
      fontSize: 16,
      color: theme.colors.text,
      fontFamily: 'Inter-Regular',
    },
    selectedOptionText: {
      color: '#3b82f6',
      fontWeight: '500',
      fontFamily: 'Inter-SemiBold',
    },
    dialectOption: {
      backgroundColor: theme.colors.surface,
      padding: 16,
      borderRadius: 12,
      marginBottom: 8,
      borderWidth: 2,
      borderColor: 'transparent',
    },
    dialectLabel: {
      fontSize: 16,
      color: theme.colors.text,
      fontWeight: '500',
      fontFamily: 'Inter-SemiBold',
    },
    dialectDescription: {
      fontSize: 14,
      color: theme.colors.textSecondary,
      marginTop: 2,
      fontFamily: 'Inter-Regular',
    },
    appearanceToggle: {
      padding: 8,
      borderRadius: 8,
      backgroundColor: isDark ? '#374151' : '#f3f4f6',
    },
    reminderToggleContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      backgroundColor: theme.colors.surface,
      padding: 20,
      borderRadius: 12,
      marginBottom: 20,
    },
    reminderToggleLabel: {
      fontSize: 16,
      fontWeight: '500',
      color: theme.colors.text,
      fontFamily: 'Inter-SemiBold',
    },
    timePickerContainer: {
      backgroundColor: theme.colors.surface,
      padding: 20,
      borderRadius: 12,
    },
    timePickerLabel: {
      fontSize: 16,
      fontWeight: '500',
      color: theme.colors.text,
      marginBottom: 16,
      fontFamily: 'Inter-SemiBold',
    },
    currentTimeText: {
      fontSize: 14,
      color: theme.colors.textSecondary,
      marginTop: 12,
      textAlign: 'center',
      fontFamily: 'Inter-Regular',
    },
    timePicker: {
      alignItems: 'center',
    },
    timeInputContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 8,
    },
    timeInput: {
      backgroundColor: isDark ? '#374151' : '#f3f4f6',
      borderRadius: 8,
      padding: 12,
      fontSize: 18,
      fontWeight: 'bold',
      textAlign: 'center',
      width: 60,
      fontFamily: 'Inter-Bold',
      color: theme.colors.text,
    },
    timeSeparator: {
      fontSize: 18,
      fontWeight: 'bold',
      marginHorizontal: 8,
      fontFamily: 'Inter-Bold',
      color: theme.colors.text,
    },
    timeFormat: {
      fontSize: 12,
      color: theme.colors.textSecondary,
      fontFamily: 'Inter-Regular',
    },
    saveButton: {
      backgroundColor: '#3b82f6',
      paddingHorizontal: 24,
      paddingVertical: 12,
      borderRadius: 8,
      marginTop: 20,
    },
    saveButtonText: {
      color: 'white',
      fontSize: 16,
      fontWeight: '600',
      textAlign: 'center',
      fontFamily: 'Inter-SemiBold',
    },
    goalDescription: {
      fontSize: 16,
      color: theme.colors.textSecondary,
      textAlign: 'center',
      marginBottom: 24,
      fontFamily: 'Inter-Regular',
    },
    goalInputContainer: {
      alignItems: 'center',
      marginBottom: 24,
    },
    goalInput: {
      backgroundColor: isDark ? '#374151' : '#f3f4f6',
      borderRadius: 12,
      padding: 16,
      fontSize: 24,
      fontWeight: 'bold',
      textAlign: 'center',
      width: 200,
      marginBottom: 8,
      fontFamily: 'Inter-Bold',
      color: theme.colors.text,
    },
    goalUnit: {
      fontSize: 16,
      color: theme.colors.textSecondary,
      fontFamily: 'Inter-Regular',
    },
    appearanceOption: {
      backgroundColor: theme.colors.surface,
      padding: 16,
      borderRadius: 12,
      marginBottom: 8,
      borderWidth: 2,
      borderColor: 'transparent',
    },
    appearanceOptionLeft: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    appearanceIcon: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: isDark ? '#374151' : '#f3f4f6',
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 12,
    },
    appearanceLabel: {
      fontSize: 16,
      color: theme.colors.text,
      fontWeight: '500',
      fontFamily: 'Inter-SemiBold',
    },
    appearanceDescription: {
      fontSize: 14,
      color: theme.colors.textSecondary,
      marginTop: 2,
      fontFamily: 'Inter-Regular',
    },
  });
