import { StyleSheet } from 'react-native';
import { Theme } from '@/components/ThemeProvider';

export const createStyles = (theme: Theme, isDark: boolean) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: isDark ? theme.colors.background : '#FFFFFF',
      position: 'relative',
    },
    bgWaveLeft: {
      position: 'absolute',
      left: 0,
      top: 0,
      bottom: 0,
      width: 40,
      opacity: isDark ? 0.15 : 0.2,
    },
    bgWaveRight: {
      position: 'absolute',
      right: 0,
      top: 0,
      bottom: 0,
      width: 40,
      opacity: isDark ? 0.15 : 0.2,
    },
    header: {
      backgroundColor: '#F3703E',
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingBottom: 20,
      paddingHorizontal: 15,
      position: 'relative',
    },
    backButton: {
      position: 'absolute',
      left: 15,
      bottom: 20,
      flexDirection: 'row',
      alignItems: 'center',
    },
    backButtonText: {
      color: '#FFFFFF',
      fontSize: 16,
      fontFamily: 'Manjari-Regular',
      marginLeft: -4,
    },
    headerTitle: {
      fontSize: 22,
      color: '#FFFFFF',
      fontFamily: 'Manjari-Bold',
    },
    headerSubtitle: {
      display: 'none',
    },
    content: {
      flex: 1,
      paddingHorizontal: 40,
    },
    section: {
      marginBottom: 20,
    },
    sectionTitle: {
      fontSize: 14,
      color: '#9ca3af',
      paddingHorizontal: 0,
      paddingVertical: 10,
      textTransform: 'uppercase',
      fontFamily: 'Manjari-Regular',
      letterSpacing: 1,
    },
    subSectionTitle: {
      fontSize: 14,
      color: '#9ca3af',
      paddingHorizontal: 0,
      paddingVertical: 10,
      textTransform: 'uppercase',
      fontFamily: 'Manjari-Regular',
      letterSpacing: 1,
    },
    sectionContent: {
      backgroundColor: 'transparent',
    },
    settingsItem: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 18,
      paddingHorizontal: 0,
      borderBottomWidth: 1,
      borderBottomColor: '#F0F0F0',
    },
    lockedItem: {
      opacity: 0.6,
    },
    settingsItemLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      flex: 1,
    },
    settingsItemIcon: {
      width: 24,
      height: 24,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 12,
    },
    lockedIcon: {
      backgroundColor: isDark ? '#1f2937' : '#f9fafb',
    },
    titleRow: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    settingsItemTitle: {
      fontSize: 16,
      color: isDark ? theme.colors.text : '#333',
      fontFamily: 'Manjari-Regular',
    },
    lockedText: {
      color: '#9ca3af',
    },
    proLabel: {
      backgroundColor: '#f59e0b',
      color: 'white',
      fontSize: 10,
      fontWeight: '600',
      paddingHorizontal: 6,
      paddingVertical: 2,
      borderRadius: 8,
      marginLeft: 8,
      fontFamily: 'Manjari-Bold',
    },
    settingsItemSubtitle: {
      display: 'none', // Subtitles are not shown in Settings.png except for specific items maybe
    },
    settingsItemRight: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    appInfo: {
      alignItems: 'center',
      paddingVertical: 32,
      paddingHorizontal: 20,
    },
    appInfoTitle: {
      fontSize: 20,
      fontWeight: 'bold',
      color: theme.colors.text,
      marginBottom: 4,
      fontFamily: 'Inter-Bold',
    },
    appInfoVersion: {
      fontSize: 14,
      color: theme.colors.textSecondary,
      marginBottom: 12,
      fontFamily: 'Inter-Regular',
    },
    appInfoDescription: {
      fontSize: 14,
      color: theme.colors.textSecondary,
      textAlign: 'center',
      lineHeight: 20,
      fontFamily: 'Inter-Regular',
    },
    modalContainer: {
      flex: 1,
      backgroundColor: isDark ? theme.colors.background : '#FFFFFF',
      position: 'relative',
    },
    modalWaveLeft: {
      position: 'absolute',
      left: 0,
      top: 0,
      bottom: 0,
      width: 40,
      opacity: isDark ? 0.15 : 0.2,
    },
    modalWaveRight: {
      position: 'absolute',
      right: 0,
      top: 0,
      bottom: 0,
      width: 40,
      opacity: isDark ? 0.15 : 0.2,
    },
    modalOrangeHeader: {
      backgroundColor: '#F3703E',
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingBottom: 20,
      paddingHorizontal: 15,
      position: 'relative',
      zIndex: 2,
    },
    modalHeaderBackButton: {
      position: 'absolute',
      left: 15,
      bottom: 20,
      flexDirection: 'row',
      alignItems: 'center',
    },
    modalHeaderTitle: {
      fontSize: 22,
      color: '#FFFFFF',
      fontFamily: 'Manjari-Bold',
    },
    modalHeaderCloseButton: {
      position: 'absolute',
      right: 15,
      bottom: 20,
      padding: 4,
    },
    modalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: 20,
      backgroundColor: theme.colors.surface,
      borderBottomWidth: 1,
      borderBottomColor: isDark ? '#374151' : '#e5e7eb',
    },
    modalTitle: {
      fontSize: 20,
      fontWeight: 'bold',
      color: theme.colors.text,
      fontFamily: 'Inter-Bold',
    },
    modalContent: {
      flex: 1,
      padding: 20,
    },
    modalText: {
      fontSize: 16,
      color: theme.colors.text,
      textAlign: 'center',
      fontFamily: 'Inter-Regular',
    },
    optionItem: {
      backgroundColor: theme.colors.surface,
      padding: 16,
      borderRadius: 12,
      marginBottom: 8,
      borderWidth: 2,
      borderColor: 'transparent',
    },
    selectedOption: {
      borderColor: '#3b82f6',
      backgroundColor: isDark ? '#1e3a8a' : '#eff6ff',
    },
    optionText: {
      fontSize: 16,
      color: theme.colors.text,
      fontFamily: 'Inter-Regular',
    },
    selectedOptionText: {
      color: '#3b82f6',
      fontWeight: '500',
      fontFamily: 'Inter-SemiBold',
    },
    dialectOption: {
      backgroundColor: '#FFFFFF',
      padding: 20,
      borderRadius: 15,
      marginBottom: 15,
      borderWidth: 1,
      borderColor: '#F0F0F0',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.05,
      shadowRadius: 5,
      elevation: 2,
    },
    selectedDialectOption: {
      backgroundColor: '#22C55E', // Green background for selected
      borderColor: '#22C55E',
    },
    dialectLabel: {
      fontSize: 18,
      color: '#333',
      fontFamily: 'Manjari-Bold',
    },
    selectedDialectLabel: {
      color: '#FFFFFF',
    },
    dialectDescription: {
      fontSize: 14,
      color: '#9ca3af',
      marginTop: 4,
      fontFamily: 'Manjari-Regular',
      textTransform: 'uppercase',
    },
    selectedDialectDescription: {
      color: 'rgba(255, 255, 255, 0.8)',
    },
    appearanceToggle: {
      padding: 8,
      borderRadius: 8,
      backgroundColor: isDark ? '#374151' : '#f3f4f6',
    },
    reminderToggleContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      backgroundColor: theme.colors.surface,
      padding: 20,
      borderRadius: 12,
      marginBottom: 20,
    },
    reminderToggleLabel: {
      fontSize: 16,
      fontWeight: '500',
      color: theme.colors.text,
      fontFamily: 'Inter-SemiBold',
    },
    timePickerContainer: {
      backgroundColor: theme.colors.surface,
      padding: 20,
      borderRadius: 12,
    },
    timePickerLabel: {
      fontSize: 16,
      fontWeight: '500',
      color: theme.colors.text,
      marginBottom: 16,
      fontFamily: 'Inter-SemiBold',
    },
    currentTimeText: {
      fontSize: 14,
      color: theme.colors.textSecondary,
      marginTop: 12,
      textAlign: 'center',
      fontFamily: 'Inter-Regular',
    },
    reminderHint: {
      fontSize: 14,
      color: theme.colors.textSecondary,
      marginTop: 16,
      marginBottom: 8,
      textAlign: 'center',
      fontFamily: 'Manjari-Regular',
      lineHeight: 20,
    },
    timePicker: {
      alignItems: 'center',
    },
    timeInputContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 8,
    },
    timeInput: {
      backgroundColor: isDark ? '#374151' : '#f3f4f6',
      borderRadius: 8,
      padding: 12,
      fontSize: 18,
      fontWeight: 'bold',
      textAlign: 'center',
      width: 60,
      fontFamily: 'Inter-Bold',
      color: theme.colors.text,
    },
    timeSeparator: {
      fontSize: 18,
      fontWeight: 'bold',
      marginHorizontal: 8,
      fontFamily: 'Inter-Bold',
      color: theme.colors.text,
    },
    timeFormat: {
      fontSize: 12,
      color: theme.colors.textSecondary,
      fontFamily: 'Inter-Regular',
    },
    saveButton: {
      backgroundColor: '#3b82f6',
      paddingHorizontal: 24,
      paddingVertical: 12,
      borderRadius: 8,
      marginTop: 20,
    },
    saveButtonText: {
      color: 'white',
      fontSize: 16,
      fontWeight: '600',
      textAlign: 'center',
      fontFamily: 'Inter-SemiBold',
    },
    goalDescription: {
      fontSize: 16,
      color: theme.colors.textSecondary,
      textAlign: 'center',
      marginBottom: 24,
      fontFamily: 'Inter-Regular',
    },
    goalInputContainer: {
      alignItems: 'center',
      marginBottom: 24,
    },
    goalInput: {
      backgroundColor: isDark ? '#374151' : '#f3f4f6',
      borderRadius: 12,
      padding: 16,
      fontSize: 24,
      fontWeight: 'bold',
      textAlign: 'center',
      width: 200,
      marginBottom: 8,
      fontFamily: 'Inter-Bold',
      color: theme.colors.text,
    },
    goalUnit: {
      fontSize: 16,
      color: theme.colors.textSecondary,
      fontFamily: 'Inter-Regular',
    },
    appearanceOption: {
      backgroundColor: theme.colors.surface,
      padding: 16,
      borderRadius: 12,
      marginBottom: 8,
      borderWidth: 2,
      borderColor: 'transparent',
    },
    appearanceOptionLeft: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    appearanceIcon: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: isDark ? '#374151' : '#f3f4f6',
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 12,
    },
    appearanceLabel: {
      fontSize: 16,
      color: theme.colors.text,
      fontWeight: '500',
      fontFamily: 'Inter-SemiBold',
    },
    appearanceDescription: {
      fontSize: 14,
      color: theme.colors.textSecondary,
      marginTop: 2,
      fontFamily: 'Inter-Regular',
    },
  });
