import { StyleSheet, Dimensions } from 'react-native';
import { Theme } from '@/components/ThemeProvider';

const { width, height } = Dimensions.get('window');

export const createStyles = (theme: Theme, isDark: boolean) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.colors.background,
    },
    content: {
      flex: 1,
    },
    topSection: {
      height: height * 0.5,
      position: 'relative',
      overflow: 'hidden',
    },
    patternContainer: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      opacity: 0.3,
    },
    patternElement: {
      position: 'absolute',
      alignItems: 'center',
      justifyContent: 'center',
    },
    patternIcon: {
      fontSize: 20,
      opacity: 0.6,
    },
    catContainer: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
    },
    catCircle: {
      width: 200,
      height: 200,
      borderRadius: 100,
      backgroundColor: 'white',
      padding: 8,
      elevation: 8,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 12,
    },
    catBackground: {
      width: '100%',
      height: '100%',
      borderRadius: 92,
      alignItems: 'center',
      justifyContent: 'center',
      position: 'relative',
    },
    cat: {
      alignItems: 'center',
      justifyContent: 'center',
      position: 'relative',
    },
    catEars: {
      flexDirection: 'row',
      gap: 20,
      marginBottom: -10,
    },
    catEar: {
      width: 20,
      height: 25,
      backgroundColor: '#000',
      borderTopLeftRadius: 15,
      borderTopRightRadius: 15,
      transform: [{ rotate: '15deg' }],
    },
    catFace: {
      width: 80,
      height: 70,
      backgroundColor: '#000',
      borderRadius: 40,
      alignItems: 'center',
      justifyContent: 'center',
      position: 'relative',
    },
    catEyes: {
      flexDirection: 'row',
      gap: 16,
      marginTop: 8,
    },
    catEye: {
      width: 12,
      height: 12,
      backgroundColor: '#fbbf24',
      borderRadius: 6,
      borderWidth: 2,
      borderColor: '#000',
    },
    catMouth: {
      marginTop: 8,
      alignItems: 'center',
    },
    catTongue: {
      width: 8,
      height: 6,
      backgroundColor: '#ec4899',
      borderRadius: 4,
    },
    catBody: {
      width: 60,
      height: 40,
      backgroundColor: '#000',
      borderRadius: 30,
      marginTop: -5,
    },
    catTail: {
      position: 'absolute',
      right: -25,
      top: 30,
      width: 40,
      height: 8,
      backgroundColor: '#000',
      borderRadius: 4,
      transform: [{ rotate: '45deg' }],
    },
    bottomSection: {
      backgroundColor: theme.colors.background,
      paddingHorizontal: 32,
      paddingVertical: 40,
      alignItems: 'center',
      flex: 1,
    },
    mainTitle: {
      fontSize: 24,
      fontWeight: '600',
      color: theme.colors.text,
      textAlign: 'center',
      fontFamily: 'Inter-SemiBold',
      marginBottom: 4,
    },
    brandTitle: {
      fontSize: 24,
      fontWeight: '600',
      color: theme.colors.text,
      textAlign: 'center',
      fontFamily: 'Inter-SemiBold',
      marginBottom: 40,
    },
    featuresList: {
      alignItems: 'flex-start',
      marginBottom: 40,
    },
    featureItem: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 16,
    },
    featureBullet: {
      width: 8,
      height: 8,
      backgroundColor: theme.colors.text,
      borderRadius: 4,
      marginRight: 16,
    },
    featureText: {
      fontSize: 18,
      color: theme.colors.text,
      fontFamily: 'Inter-Regular',
    },
    buyButton: {
      backgroundColor: '#ea580c',
      paddingHorizontal: 48,
      paddingVertical: 16,
      borderRadius: 25,
      marginBottom: 24,
      minWidth: 200,
      alignItems: 'center',
    },
    buyButtonDisabled: {
      opacity: 0.6,
    },
    buyButtonText: {
      color: 'white',
      fontSize: 18,
      fontWeight: '600',
      fontFamily: 'Inter-SemiBold',
    },
    pricingInfo: {
      alignItems: 'center',
      marginBottom: 60,
    },
    priceText: {
      fontSize: 16,
      color: theme.colors.textSecondary,
      fontFamily: 'Inter-Regular',
      marginBottom: 4,
    },
    subscriptionText: {
      fontSize: 16,
      color: theme.colors.textSecondary,
      fontFamily: 'Inter-Regular',
    },
    restoreButton: {
      paddingVertical: 12,
    },
    restoreButtonText: {
      fontSize: 16,
      color: '#ea580c',
      fontFamily: 'Inter-Regular',
      textAlign: 'center',
    },
    // Pro user styles
    header: {
      alignItems: 'center',
      paddingVertical: 48,
      borderBottomLeftRadius: 24,
      borderBottomRightRadius: 24,
    },
    headerTitle: {
      fontSize: 28,
      fontWeight: 'bold',
      color: 'white',
      marginTop: 16,
      marginBottom: 8,
      fontFamily: 'Inter-Bold',
    },
    headerSubtitle: {
      fontSize: 16,
      color: 'rgba(255, 255, 255, 0.9)',
      fontFamily: 'Inter-Regular',
    },
    proStatusContainer: {
      padding: 20,
      margin: 20,
      borderRadius: 16,
    },
    proStatusTitle: {
      fontSize: 20,
      fontWeight: 'bold',
      marginBottom: 20,
      textAlign: 'center',
      fontFamily: 'Inter-Bold',
    },
    featureIcon: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: '#dcfce7',
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 16,
    },
    thankYouContainer: {
      margin: 20,
      padding: 24,
      borderRadius: 16,
      alignItems: 'center',
    },
    thankYouText: {
      fontSize: 16,
      textAlign: 'center',
      fontFamily: 'Inter-Regular',
    },
  });
