#name: React + Typescript CI/CD UI Build Pipeline
#
#on:
#  push:
#    branches:
#      - main
#  pull_request:
#    paths:
#      - 'UI/**'
#
#jobs:
#  build-and-test:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v3
#
#      - name: Set up Node.js
#        uses: actions/setup-node@v3
#        with:
#          node-version: '18'  # Specify the Node.js version you are using
#
#      - name: Install dependencies
#        run: |
#          cd UI  # Navigate to the UI subfolder
#          npm install
#
#      - name: Build the project
#        run: |
#          cd UI  # Navigate to the UI subfolder
#          npm run build
#
#      # - name: Run tests
#      #   run: |
#      #     cd UI  # Navigate to the UI subfolder
#      #     npm test
